// このファイルは自動生成される。手で編集しない。
// 再生成: dart run tool/fetch_pro_reactions.dart
//
// 出典: https://karotter.com のバンドル内 proReactions チャンク。
// 一覧を返す API が無いため埋め込んでいる。
//
// 仕様: specs/005-rich-text/requirements.md

/// PRO プラン限定のカスタムリアクション 1 件。
class ProReaction {
  const ProReaction({
    required this.code,
    required this.slug,
    required this.label,
    required this.labelEn,
    required this.assetUrl,
  });

  /// `ReactionSummary.emoji` に入る識別子。`pro:otsukaresama` の形。
  final String code;

  final String slug;

  /// 画面に出す名前。
  final String label;

  final String labelEn;

  /// Karotter Web のホスト基準の相対パス。`karotterUrl()` で絶対化する。
  final String assetUrl;
}

/// 全 87 件。
const proReactions = <ProReaction>[
  ProReaction(
    code: 'pro:arigato',
    slug: 'arigatou',
    label: 'ありがとう',
    labelEn: 'Thanks',
    assetUrl: '/reactions/pro/arigato.png',
  ),
  ProReaction(
    code: 'pro:ohayo',
    slug: 'ohayo',
    label: 'おはよ',
    labelEn: 'Good morning',
    assetUrl: '/reactions/pro/ohayo.png',
  ),
  ProReaction(
    code: 'pro:saikousugiru',
    slug: 'saikousugiru',
    label: '最高',
    labelEn: 'Awesome',
    assetUrl: '/reactions/pro/saikousugiru.png',
  ),
  ProReaction(
    code: 'pro:otsukaresama',
    slug: 'otsukaresama',
    label: 'おつかれ様',
    labelEn: 'Nice work',
    assetUrl: '/reactions/pro/otsukaresama.png',
  ),
  ProReaction(
    code: 'pro:tasukaru',
    slug: 'tasukaru',
    label: '助かる',
    labelEn: 'Helpful',
    assetUrl: '/reactions/pro/tasukaru.png',
  ),
  ProReaction(
    code: 'pro:saikoukaryoku',
    slug: 'saikoukaryoku',
    label: '最高火力',
    labelEn: 'Fire',
    assetUrl: '/reactions/pro/saikoukaryoku.png',
  ),
  ProReaction(
    code: 'pro:syogyomujo',
    slug: 'syogyomujo',
    label: '諸行無常',
    labelEn: 'syogyomujo',
    assetUrl: '/reactions/pro/syogyomujo.png',
  ),
  ProReaction(
    code: 'pro:owatta',
    slug: 'owatta',
    label: '終わった',
    labelEn: 'finish',
    assetUrl: '/reactions/pro/owatta.png',
  ),
  ProReaction(
    code: 'pro:yurusanai',
    slug: 'yurusanai',
    label: '許さない',
    labelEn: 'yurusanai',
    assetUrl: '/reactions/pro/yurusanai.png',
  ),
  ProReaction(
    code: 'pro:yoroshiku',
    slug: 'yoroshiku',
    label: 'よろしく',
    labelEn: 'yoroshiku',
    assetUrl: '/reactions/pro/yoroshiku.png',
  ),
  ProReaction(
    code: 'pro:gomen',
    slug: 'gomen',
    label: 'ごめんね',
    labelEn: 'sorry',
    assetUrl: '/reactions/pro/gomen.png',
  ),
  ProReaction(
    code: 'pro:yurushite',
    slug: 'yurushite',
    label: 'ゆるして',
    labelEn: 'yurushite',
    assetUrl: '/reactions/pro/yurushite.png',
  ),
  ProReaction(
    code: 'pro:tasukete',
    slug: 'tasukete',
    label: 'たすけて',
    labelEn: 'help',
    assetUrl: '/reactions/pro/tasukete.png',
  ),
  ProReaction(
    code: 'pro:karotter',
    slug: 'karotter',
    label: 'かろったー',
    labelEn: 'karotter',
    assetUrl: '/reactions/pro/karotter.png',
  ),
  ProReaction(
    code: 'pro:karon',
    slug: 'karon',
    label: 'かろん',
    labelEn: 'karon',
    assetUrl: '/reactions/pro/karon.png',
  ),
  ProReaction(
    code: 'pro:iie',
    slug: 'iie',
    label: 'いいえ',
    labelEn: 'no',
    assetUrl: '/reactions/pro/iie.png',
  ),
  ProReaction(
    code: 'pro:iiyo',
    slug: 'iiyo',
    label: 'いいよ',
    labelEn: 'ok',
    assetUrl: '/reactions/pro/iiyo.png',
  ),
  ProReaction(
    code: 'pro:nani',
    slug: 'nani',
    label: 'なに？',
    labelEn: 'what?',
    assetUrl: '/reactions/pro/nani.png',
  ),
  ProReaction(
    code: 'pro:tensai',
    slug: 'tensai',
    label: '天才',
    labelEn: 'tensai',
    assetUrl: '/reactions/pro/tensai.png',
  ),
  ProReaction(
    code: 'pro:arara',
    slug: 'arara',
    label: 'あらら',
    labelEn: 'arara',
    assetUrl: '/reactions/pro/arara.png',
  ),
  ProReaction(
    code: 'pro:ee',
    slug: 'ee',
    label: 'えぇ...',
    labelEn: 'ee...',
    assetUrl: '/reactions/pro/ee.png',
  ),
  ProReaction(
    code: 'pro:gekiatsu',
    slug: 'gekiatsu',
    label: '激アツ',
    labelEn: 'superhot',
    assetUrl: '/reactions/pro/gekiatsu.png',
  ),
  ProReaction(
    code: 'pro:koreha',
    slug: 'koreha',
    label: 'これは',
    labelEn: 'this',
    assetUrl: '/reactions/pro/this.png',
  ),
  ProReaction(
    code: 'pro:wakaru',
    slug: 'wakaru',
    label: 'わかる',
    labelEn: 'wakaru',
    assetUrl: '/reactions/pro/wakaru.png',
  ),
  ProReaction(
    code: 'pro:mazide',
    slug: 'mazide',
    label: 'マジで',
    labelEn: 'mazide',
    assetUrl: '/reactions/pro/mazide.png',
  ),
  ProReaction(
    code: 'pro:dakara',
    slug: 'dakara',
    label: 'だから',
    labelEn: 'dakara',
    assetUrl: '/reactions/pro/dakara.png',
  ),
  ProReaction(
    code: 'pro:hosii',
    slug: 'hosii',
    label: 'ほしい',
    labelEn: 'want',
    assetUrl: '/reactions/pro/hosii.png',
  ),
  ProReaction(
    code: 'pro:yamete',
    slug: 'yamete',
    label: 'やめて',
    labelEn: 'stop',
    assetUrl: '/reactions/pro/yamete.png',
  ),
  ProReaction(
    code: 'pro:suki',
    slug: 'suki',
    label: 'すき',
    labelEn: 'like',
    assetUrl: '/reactions/pro/suki.png',
  ),
  ProReaction(
    code: 'pro:hai',
    slug: 'hai',
    label: 'はい',
    labelEn: 'yes',
    assetUrl: '/reactions/pro/hai.png',
  ),
  ProReaction(
    code: 'pro:kore',
    slug: 'kore',
    label: 'これ',
    labelEn: 'kore',
    assetUrl: '/reactions/pro/kore.png',
  ),
  ProReaction(
    code: 'pro:e',
    slug: 'e',
    label: 'え？',
    labelEn: 'what?',
    assetUrl: '/reactions/pro/e.png',
  ),
  ProReaction(
    code: 'pro:ai',
    slug: 'ai',
    label: '愛',
    labelEn: 'love',
    assetUrl: '/reactions/pro/ai.png',
  ),
  ProReaction(
    code: 'pro:kusa',
    slug: 'kusa',
    label: '草',
    labelEn: 'kusa',
    assetUrl: '/reactions/pro/kusa.png',
  ),
  ProReaction(
    code: 'pro:kane',
    slug: 'kane',
    label: '金',
    labelEn: 'kane',
    assetUrl: '/reactions/pro/kane.png',
  ),
  ProReaction(
    code: 'pro:hiku',
    slug: 'hiku',
    label: '引',
    labelEn: 'hiku',
    assetUrl: '/reactions/pro/hiku.png',
  ),
  ProReaction(
    code: 'pro:kansya',
    slug: 'kansya',
    label: '感謝',
    labelEn: 'thanks',
    assetUrl: '/reactions/pro/kansya.png',
  ),
  ProReaction(
    code: 'pro:owari',
    slug: 'owari',
    label: '終わり',
    labelEn: 'the end',
    assetUrl: '/reactions/pro/owari.png',
  ),
  ProReaction(
    code: 'pro:igyo',
    slug: 'igyo',
    label: '偉業',
    labelEn: 'great achievement',
    assetUrl: '/reactions/pro/igyo.png',
  ),
  ProReaction(
    code: 'pro:kandou',
    slug: 'kandou',
    label: '感動',
    labelEn: 'moved',
    assetUrl: '/reactions/pro/kandou.png',
  ),
  ProReaction(
    code: 'pro:sorena',
    slug: 'sorena',
    label: 'それな',
    labelEn: 'exactly',
    assetUrl: '/reactions/pro/sorena.png',
  ),
  ProReaction(
    code: 'pro:umai',
    slug: 'umai',
    label: 'うまい',
    labelEn: 'nice',
    assetUrl: '/reactions/pro/umai.png',
  ),
  ProReaction(
    code: 'pro:bimi',
    slug: 'bimi',
    label: '美味',
    labelEn: 'delicious',
    assetUrl: '/reactions/pro/bimi.png',
  ),
  ProReaction(
    code: 'pro:bimyou',
    slug: 'bimyou',
    label: '微妙',
    labelEn: 'not sure',
    assetUrl: '/reactions/pro/bimyou.png',
  ),
  ProReaction(
    code: 'pro:kirei',
    slug: 'kirei',
    label: 'きれい',
    labelEn: 'beautiful',
    assetUrl: '/reactions/pro/kirei.png',
  ),
  ProReaction(
    code: 'pro:dame',
    slug: 'dame',
    label: 'ダメ',
    labelEn: 'no good',
    assetUrl: '/reactions/pro/dame.png',
  ),
  ProReaction(
    code: 'pro:desu',
    slug: 'desu',
    label: 'です',
    labelEn: 'desu',
    assetUrl: '/reactions/pro/desu.png',
  ),
  ProReaction(
    code: 'pro:kanasii',
    slug: 'kanasii',
    label: '悲しい',
    labelEn: 'sad',
    assetUrl: '/reactions/pro/kanasii.png',
  ),
  ProReaction(
    code: 'pro:kawaii',
    slug: 'kawaii',
    label: 'かわいい',
    labelEn: 'cute',
    assetUrl: '/reactions/pro/kawaii.png',
  ),
  ProReaction(
    code: 'pro:medetai',
    slug: 'medetai',
    label: 'めでたい',
    labelEn: 'congrats',
    assetUrl: '/reactions/pro/medetai.png',
  ),
  ProReaction(
    code: 'pro:kurusii',
    slug: 'kurusii',
    label: '苦しい',
    labelEn: 'painful',
    assetUrl: '/reactions/pro/kurusii.png',
  ),
  ProReaction(
    code: 'pro:sugoi',
    slug: 'sugoi',
    label: 'すごい',
    labelEn: 'amazing',
    assetUrl: '/reactions/pro/sugoi.png',
  ),
  ProReaction(
    code: 'pro:watashihakami',
    slug: 'watashihakami',
    label: '私は神',
    labelEn: 'I am god',
    assetUrl: '/reactions/pro/watashihakami.png',
  ),
  ProReaction(
    code: 'pro:mazi',
    slug: 'mazi',
    label: 'マジ？',
    labelEn: 'seriously',
    assetUrl: '/reactions/pro/mazi.png',
  ),
  ProReaction(
    code: 'pro:sagidesu',
    slug: 'sagidesu',
    label: '詐欺です',
    labelEn: 'scam',
    assetUrl: '/reactions/pro/sagidesu.png',
  ),
  ProReaction(
    code: 'pro:sayonara',
    slug: 'sayonara',
    label: 'さよなら',
    labelEn: 'goodbye',
    assetUrl: '/reactions/pro/sayonara.png',
  ),
  ProReaction(
    code: 'pro:tigaimasu',
    slug: 'tigaimasu',
    label: '違います',
    labelEn: 'not true',
    assetUrl: '/reactions/pro/tigaimasu.png',
  ),
  ProReaction(
    code: 'pro:kowasugiru',
    slug: 'kowasugiru',
    label: '怖すぎる',
    labelEn: 'too scary',
    assetUrl: '/reactions/pro/kowasugiru.png',
  ),
  ProReaction(
    code: 'pro:daijoubu',
    slug: 'daijoubu',
    label: '大丈夫？',
    labelEn: 'are you ok?',
    assetUrl: '/reactions/pro/daijoubu.png',
  ),
  ProReaction(
    code: 'pro:sinpaidayo',
    slug: 'sinpaidayo',
    label: '心配だよ',
    labelEn: 'worry',
    assetUrl: '/reactions/pro/sinpaidayo.png',
  ),
  ProReaction(
    code: 'pro:ganbare',
    slug: 'ganbare',
    label: 'がんばれ',
    labelEn: 'fight',
    assetUrl: '/reactions/pro/ganbare.png',
  ),
  ProReaction(
    code: 'pro:bananala',
    slug: 'bananala',
    label: 'ばななぁ',
    labelEn: 'Banana',
    assetUrl: '/reactions/pro/bananala.png',
  ),
  ProReaction(
    code: 'pro:critical',
    slug: 'critical',
    label: 'クリティカル',
    labelEn: 'Critical',
    assetUrl: '/reactions/pro/critical.png',
  ),
  ProReaction(
    code: 'pro:daisuki',
    slug: 'daisuki',
    label: '大好き',
    labelEn: 'Love it',
    assetUrl: '/reactions/pro/daisuki.png',
  ),
  ProReaction(
    code: 'pro:fanburu',
    slug: 'fanburu',
    label: 'ファンブル',
    labelEn: 'Fumble',
    assetUrl: '/reactions/pro/fanburu.png',
  ),
  ProReaction(
    code: 'pro:furaidopotato',
    slug: 'furaidopotato',
    label: 'フライドポテト',
    labelEn: 'French fries',
    assetUrl: '/reactions/pro/furaidopotato.png',
  ),
  ProReaction(
    code: 'pro:haigimon',
    slug: 'haigimon',
    label: 'はい？',
    labelEn: 'Huh?',
    assetUrl: '/reactions/pro/hai-gimon.png',
  ),
  ProReaction(
    code: 'pro:hurokuu',
    slug: 'hurokuu',
    label: '風呂食う',
    labelEn: 'Eat a bath',
    assetUrl: '/reactions/pro/hurokuu.png',
  ),
  ProReaction(
    code: 'pro:kakkoyosugiru',
    slug: 'kakkoyosugiru',
    label: 'かっこよすぎる',
    labelEn: 'Too cool',
    assetUrl: '/reactions/pro/kakkoyosugiru.png',
  ),
  ProReaction(
    code: 'pro:karoart',
    slug: 'karoart',
    label: 'かろあーと',
    labelEn: 'Karoart',
    assetUrl: '/reactions/pro/karoart.png',
  ),
  ProReaction(
    code: 'pro:karoearth',
    slug: 'karoearth',
    label: 'かろEarth',
    labelEn: 'KaroEarth',
    assetUrl: '/reactions/pro/karoearth.png',
  ),
  ProReaction(
    code: 'pro:kekkonsitai',
    slug: 'kekkonsitai',
    label: '結婚したい',
    labelEn: 'I want to marry',
    assetUrl: '/reactions/pro/kekkonsitai.png',
  ),
  ProReaction(
    code: 'pro:medaka',
    slug: 'medaka',
    label: 'メダカ',
    labelEn: 'Medaka',
    assetUrl: '/reactions/pro/medaka.png',
  ),
  ProReaction(
    code: 'pro:melonsoda',
    slug: 'melonsoda',
    label: 'メロンソーダ',
    labelEn: 'Melon soda',
    assetUrl: '/reactions/pro/melonsoda.png',
  ),
  ProReaction(
    code: 'pro:odaizini',
    slug: 'odaizini',
    label: 'お大事に',
    labelEn: 'Get well soon',
    assetUrl: '/reactions/pro/odaizini.png',
  ),
  ProReaction(
    code: 'pro:oyasumi',
    slug: 'oyasumi',
    label: 'おやすみ',
    labelEn: 'Good night',
    assetUrl: '/reactions/pro/oyasumi.png',
  ),
  ProReaction(
    code: 'pro:saida',
    slug: 'saida',
    label: 'サイダー',
    labelEn: 'Cider',
    assetUrl: '/reactions/pro/saida-.png',
  ),
  ProReaction(
    code: 'pro:shihiro',
    slug: 'shihiro',
    label: 'しひろ',
    labelEn: 'Shihiro',
    assetUrl: '/reactions/pro/shihiro.png',
  ),
  ProReaction(
    code: 'pro:sonnnawake',
    slug: 'sonnnawake',
    label: 'そんなわけ',
    labelEn: 'No way',
    assetUrl: '/reactions/pro/sonnnawake.png',
  ),
  ProReaction(
    code: 'pro:syunkasyuutouasahiruban',
    slug: 'syunkasyuutouasahiruban',
    label: '春夏秋冬朝昼晩',
    labelEn: 'All year, all day',
    assetUrl: '/reactions/pro/syunkasyuutouasahiruban.png',
  ),
  ProReaction(
    code: 'pro:takuan',
    slug: 'takuan',
    label: 'たくあん',
    labelEn: 'Takuan',
    assetUrl: '/reactions/pro/takuan.png',
  ),
  ProReaction(
    code: 'pro:uo',
    slug: 'uo',
    label: 'うおー!!',
    labelEn: 'Whoa!!',
    assetUrl: '/reactions/pro/uo-!!.png',
  ),
  ProReaction(
    code: 'pro:urayamasii',
    slug: 'urayamasii',
    label: 'うらやましい',
    labelEn: 'Jealous',
    assetUrl: '/reactions/pro/urayamasii.png',
  ),
  ProReaction(
    code: 'pro:yasasii',
    slug: 'yasasii',
    label: 'やさしい',
    labelEn: 'Kind',
    assetUrl: '/reactions/pro/yasasii.png',
  ),
  ProReaction(
    code: 'pro:youkoso',
    slug: 'youkoso',
    label: 'ようこそ',
    labelEn: 'Welcome',
    assetUrl: '/reactions/pro/youkoso.png',
  ),
  ProReaction(
    code: 'pro:yuunousugiru',
    slug: 'yuunousugiru',
    label: '有能すぎる',
    labelEn: 'Too capable',
    assetUrl: '/reactions/pro/yuunousugiru.png',
  ),
  ProReaction(
    code: 'pro:thinkkaron1',
    slug: 'thinkkaron1',
    label: '考えるかろん',
    labelEn: 'thinking karon',
    assetUrl: '/reactions/pro/thinkkaron1.png',
  ),
];

/// 識別子で引くための索引。
///
/// リアクションはタイムラインの全カロートで描かれるので、
/// 毎回 87 件を線形に探さない。
final _byCode = {for (final r in proReactions) r.code: r};

/// 知らない識別子なら null。
ProReaction? proReactionOf(String code) => _byCode[code];

/// pro リアクションの識別子か。
bool isProReaction(String code) => _byCode.containsKey(code);
