name: アプリを自動で作成

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"

permissions:
  contents: write

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.5"
          channel: "stable"

      - name: Flutter pub get
        run: flutter pub get

      - name: Lint check
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      # Android build
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          cd build/app/outputs/flutter-apk/
          mv app-arm64-v8a-release.apk   karotator-arm64-v8a.apk
          mv app-armeabi-v7a-release.apk karotator-armeabi-v7a.apk
          mv app-x86_64-release.apk      karotator-x86_64.apk

      # iOS build
      - name: Check xcodebuild version (for debug)
        run: xcodebuild -version

      - name: Build .app (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Convert .app to .ipa
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/Runner.app
          zip -r karotator.ipa Payload

      - name: Generate tag
        id: tag
        run: echo "tag=pre-$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Pre-release ${{ steps.tag.outputs.tag }}
          prerelease: true
          files: |
            build/ios/iphoneos/karotator.ipa
            build/app/outputs/flutter-apk/karotator-arm64-v8a.apk
            build/app/outputs/flutter-apk/karotator-armeabi-v7a.apk
            build/app/outputs/flutter-apk/karotator-x86_64.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
